# Generated by Django 3.2.2 on 2021-05-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(default='Altug Publishing', max_length=40),
        ),
    ]
