# Generated by Django 3.2.2 on 2021-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_comment_user'),
        ('home', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
