# Generated by Django 3.2.2 on 2021-05-29 10:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='type',
            field=models.CharField(choices=[('etkinlik', 'etkinlik'), ('menu', 'menu'), ('haber', 'haber'), ('duyuru', 'duyuru')], max_length=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.menu'),
        ),
    ]
